### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by shrippen** [matztam/ARD-Audiothek-RSS#1]
Hi,
I just tried your script to generate an RSS Feed for Kalk & Welk but the script generated this rss feed:

`
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrss/" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" version="2.0"><channel><title></title><link>https://www.ardaudiothek.de/sendung/</link><image><url></url><title></title><link>https://www.ardaudiothek.de/sendung/</link></image><description></description><atom:link href="//192.168.178.5:8005/ardaudiothek-rss.php?show=10777871" rel="self" type="application/rss+xml"/></channel></rss>
`

**Comment by matztam** [comment]
There seems to be a problem with the Audiothek API at the moment. 

https://api.ardaudiothek.de/programsets/10777871 returns 
> `{"errors":[{"message":"Value \"GROUP_NUMBER_ASC\" does not exist in \"ItemsOrderBy\" enum. Did you mean the enum value \"MAX_GROUP_NUMBER_ASC\", \"EPISODE_NUMBER_ASC\", \"GROUP_ID_ASC\", \"MAX_GROUP_NUMBER_DESC\", or \"GROUP_ID_DESC\"?","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Value \"GROUP_NUMBER_ASC\" does not exist in \"ItemsOrderBy\" enum. Did you mean the enum value \"MAX_GROUP_NUMBER_ASC\", \"EPISODE_NUMBER_ASC\", \"GROUP_ID_ASC\", \"MAX_GROUP_NUMBER_DESC\", or \"GROUP_ID_DESC\"?","    at GraphQLEnumType.parseLiteral (/app/node_modules/graphql/type/definition.js:1040:13)","    at isValidValueNode (/app/node_modules/graphql/validation/rules/ValuesOfCorrectTypeRule.js:125:28)","    at Object.EnumValue (/app/node_modules/graphql/validation/rules/ValuesOfCorrectTypeRule.js:84:14)","    at Object.enter (/app/node_modules/graphql/language/visitor.js:323:29)","    at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:370:25)","    at visit (/app/node_modules/graphql/language/visitor.js:243:26)","    at validate (/app/node_modules/graphql/validation/validate.js:69:24)","    at validate (/app/node_modules/apollo-server-core/dist/requestPipeline.js:185:39)","    at processGraphQLRequest (/app/node_modules/apollo-server-core/dist/requestPipeline.js:90:34)","    at runMicrotasks (<anonymous>)"]}}}]}`

**Comment by shrippen** [comment]
Ah, okay. Then I will test again in a few days. Thanks for the work!
________________________________

**Comment by matztam** [comment]
Since the problems with the REST API persist and the error message suggests that the REST API is just a wrapper of the GraphQL API, I have now switched to GraphQL.
