### ISSUE TITLE
Interested in a pull request for auto build and publish of the docker image?

### ISSUE THREAD

**Issue by frauhottelmann** [matztam/ARD-Audiothek-RSS#15]
Hey, I have forked the [repo](https://github.com/frauhottelmann/ARD-Audiothek-RSS) to setup auto building of the image and publishing it to github container registry. All it does right now is to automatically build and push the image on every commit to the master branch.

I don't care much to keep this up to date since this isn't my project, but I could create a pull request so this would be set up here.

Any interest?

**Comment by matztam** [comment]
Sounds good! Please send me a pull request.
